### ISSUE TITLE
Tasks Epic

### ISSUE THREAD

**Issue by geohacker** [orma/openroads-vn-analytics#423]
This ticket captures all the Tasks related issues to investigate closely for related issues, workflow, or improved documentation. 

* [x] Confusion around number of Tasks https://github.com/orma/openroads-vn-analytics/issues/420
* [x] Task selection based on districts https://github.com/orma/openroads-vn-analytics/issues/402
* [x] Make the instructions better and clear https://github.com/orma/openroads-vn-analytics/issues/400
* [x] Make Task IDs stable https://github.com/orma/openroads-vn-analytics/issues/282
* [x] Improve the basemap https://github.com/orma/openroads-vn-analytics/issues/370
* [x] Misleading tasks https://github.com/orma/openroads-vn-analytics/issues/424
* [x] Task counter inflated https://github.com/orma/openroads-vn-analytics/issues/425
* [x] Show satellite layer https://github.com/orma/openroads-vn-analytics/issues/251
* [ ] Permalinks
* [x] Potentially list all tasks

cc @dereklieu @olafveerman @PCDuc

**Comment by dereklieu** [comment]
@geohacker Here's what I propose to address these tickets. Let me know what you think. Very open to suggestions or re-imaginations on any of these. 

### Reprocess recently-edited features only

Instead of processing the entire database each time, we should instead query only those nodes that have been edited since the last time the script ran, using the node's `timestamp` property. (We'll have to make sure this property is being set correctly.)

From those nodes we can query each attached way, then query nearby ways, and use that as the basis for task detection. This should make "wont-fix" labels permanent (until that feature gets an edit).

### Use way IDs to dedupe tasks

To fix cases where *n* overlapping roads create *n* separate tasks, we should use way IDs as a means of deduping, and creating a single task from this scenario. Ie, if two tasks both involve ways A, B, and C, they are considered the same task.

We can potentially go further and combine tasks where, ie, task 1 involves ways A, B, and C, while task 2 involves ways A, B, C, and D. I'm not sure how often this particular scenario occurs, however, and it may be the case that reducing tasks with the exact same way IDs will be good enough.

### UI improvements

We should do an audit of the interface, including the two main task resolutions (intersection and dedupe) to make sure that instructions are clear and understandable. Furthermore, it should be clear what mode you're in at any point.

We can also look into improving the display of currently selected features, in addition to improving the display of the current mode.

### Basemap improvements

Add contrast to the basemap in order to improve wayfinding. We should also consider adding layer toggles for satellite and OSM streets layers.

**Comment by geohacker** [comment]
All of the above items are shipped 🎉
